CREATE FUNCTION [dbo].[Get_Total_Floorset_LF] (@FLOORSET_TUID INT)
RETURNS TABLE
AS
RETURN(
	SELECT SUM((ff.HANGER_STACK * f.LF_CAP)) AS TOTAL_INSTANCE_LF
		FROM Floorsets_Fixtures AS ff
		JOIN Fixtures AS f
			ON ff.FIXTURE_TUID = f.TUID
	WHERE ff.FLOORSET_TUID = @FLOORSET_TUID
);
GO